### ISSUE TITLE
[EEA] Table Number

### ISSUE THREAD

**Issue by collardeg** [collardeg/zh#13]
- Create a new table number field for each user.
- Do NOT add it to the collard profile page directly
- Display it inside the QR code popup in the lower left corner without saying 'table number' aw ay haga - just the field). We do not want people to know that this is their table number - only internally.
- Also note that the table number can be 'L16' masalan fa keep it as text not integer.
- Add the new field to the allimport template
- Please send me an updated CSV for allimport that includes the new field

**Comment by jowebme** [comment]
![Screenshot 2021-06-10 161640.jpg](https://images.zenhubusercontent.com/60be312c3ffc7e718570b1c2/471bace8-b334-4e65-8ba7-eb22d92b6ecb)

**Comment by jowebme** [comment]
Looks better this way on bottom left side looks very weird
