### ISSUE TITLE
[Pass] Add Sounds

### ISSUE THREAD

**Issue by collardeg** [collardeg/zh#2]
Add success sound, card expired sound and card not valid (duplicate) sound. See the video I sent for example sounds (simple, short, distinct).

**Comment by jowebme** [comment]
[https://app.zenhub.com/files/374604010/efa51f3d-517f-4954-8770-1a98a4acfde2/download](https://app.zenhub.com/files/374604010/efa51f3d-517f-4954-8770-1a98a4acfde2/download)

**Comment by jowebme** [comment]
I used those three sounds, please if you wanna change any of them, get the file as mp3 rename it with the same name & send it to me !
