### ISSUE TITLE
[EEA] Get Directions Popup

### ISSUE THREAD

**Issue by collardeg** [collardeg/zh#5]
'Get Directions' opens a popup. This is great - exactly what we need but please remove the part saying "before going to that link" - this part of the message was for you.

**Comment by jowebme** [comment]
![Screenshot 2021-06-08 030617.jpg](https://images.zenhubusercontent.com/60be312c3ffc7e718570b1c2/201884ff-97d1-483b-a416-7a36352cc70a)

**Comment by jowebme** [comment]
I added a map to the popup, it looks great i think
