### ISSUE TITLE
[EEA] Update Date/Time

### ISSUE THREAD

**Issue by collardeg** [collardeg/zh#6]
Change the Block containing the date and time.

- Change date to June 12
- Change time to :
"6PM Red Carpet | Cocktail Reception"
"8.15PM Awards Ceremony"

**Comment by jowebme** [comment]
![Screenshot 2021-06-08 030510.jpg](https://images.zenhubusercontent.com/60be312c3ffc7e718570b1c2/95eb58e3-bea5-4cc3-8e16-085d6350b50f)

**Comment by jowebme** [comment]
Please Provide the rest of the data

**Comment by collardeg** [comment]
I was talking about this section - do you need all that information for it?

<img width="505" alt="Screen Shot 2021-06-08 at 9 48 09 AM" src="https://user-images.githubusercontent.com/85486096/121144873-acf1fe00-c83e-11eb-9c5b-d7b42590d0d5.png">

**Comment by jowebme** [comment]
Its okay 5alas msh ana kdh tmm ?
