### ISSUE TITLE
[EEA] First Tap Page

### ISSUE THREAD

**Issue by collardeg** [collardeg/zh#9]
From the first tap page, remove everything in yellow, keep everything in blue at the top and then please add the invitation attached. Make it fill the screen width and have the height adjust accordingly please.
Underneath the invitation will be the button to login with phone.

[Invitation to add](https://app.zenhub.com/files/374604010/a81cf846-d91d-420e-8deb-14b8e859ad7b/download)

![IMG_8308.jpg](https://images.zenhubusercontent.com/60bde37067611e0bd60f588d/1e976851-d012-4f2d-839b-c12b9916d37b)

**Comment by jowebme** [comment]
I added the pdf as JPG with a lightbox so user can open it & zoom in it if needed, or we can disable the lightbox & cut the pattern in the image as it forces the image to stay zoomed out

**Comment by jowebme** [comment]
![invitation.jpg](https://images.zenhubusercontent.com/60be312c3ffc7e718570b1c2/067ba51a-af76-4b1f-8976-89eed048eabb)

**Comment by jowebme** [comment]
As example here is if we cut it, it will look perfect without the need to click on it to view it in a good way
